# Site settings
title: R.A.T. Museum
description: Real Art, Tiny Museum - A miniature public art gallery showcasing creativity in the smallest of spaces
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ratmuseum.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# Collections
collections:
  exhibitions:
    output: true
    permalink: /exhibitions/:title/
    sort_by: date

# Set default values for exhibitions
defaults:
  - scope:
      path: ""
      type: "exhibitions"
    values:
      layout: "exhibition"
